#!/bin/bash
# what to run in order, taken from the website
#1. comment out when finished
#gunzip -c Height.gz | awk '{seen[$3]++; if(seen[$3]==1){ print}}'|gzip -> Height.nodup.gz

# 2. retain nonambigous SNPs

gunzip -c Height.nodup.gz | \
awk '!( ($4=="A" && $5=="T") || \
	($4=="T" && $5=="A") || \
	($4=="G" && $5=="C") || \
	($4=="C" && $5=="G")) {print}' |\
gzip > Height.QC.gz


